server {
  listen 80;
  listen [::]:80;
  server_name localhost;
	access_log  /opt/nginx_access.log;
	error_log /opt/nginx_error.log;
	charset  utf-8;
	gzip on;
	gzip_types text/plain application/x-javascript text/css text/javascript application/x-httpd-php application/json text/json image/jpeg image/gif image/png application/octet-str
	error_page  404           /404.html;
	error_page   500 502 503 504  /50x.html;

  location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
  }

  location /api/ {
      proxy_pass http://172.16.80.20:21090;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      rewrite ^/api/?(.*)$ /$1 break;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
      root   /usr/share/nginx/html;
  }
}
