# 直接使用nginx镜像
FROM nginx:stable-alpine

# 复制已构建好的dist目录到nginx的静态文件目录
COPY personal-heath-view/dist /usr/share/nginx/html

# 添加自定义nginx配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 